@FileService_HostAddress = https://localhost:7002

GET {{FileService_HostAddress}}/badrequest/
Accept: application/json

###

POST {{FileService_HostAddress}}/api/authentication/sign-in/
Accept: application/json
Content-Type: application/json
