// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musdis.MusicService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicService.Migrations
{
    [DbContext(typeof(MusicServiceDbContext))]
    [Migration("20240209134147_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ArtistTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7dbf634-cb38-4340-a19e-e8eec6a4bc45"),
                            Name = "Band",
                            Slug = "band"
                        },
                        new
                        {
                            Id = new Guid("ad2b0436-9220-4d21-bb4c-1a85a916c566"),
                            Name = "Musician",
                            Slug = "musician"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistUser", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ArtistId", "UserId");

                    b.ToTable("ArtistUsers");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReleaseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseArtist", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("ReleaseId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ReleaseArtists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ReleaseTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6660865f-f695-4161-b296-1ad2c022b5dd"),
                            Name = "EP",
                            Slug = "ep"
                        },
                        new
                        {
                            Id = new Guid("03c75592-843b-4a8c-9927-6559eca8b5d3"),
                            Name = "Album",
                            Slug = "album"
                        },
                        new
                        {
                            Id = new Guid("4eaf9b6c-89d4-4de8-aee2-bc29fca07a1e"),
                            Name = "Single",
                            Slug = "single"
                        },
                        new
                        {
                            Id = new Guid("8f057213-54ef-4536-a318-2676d6a4fd8e"),
                            Name = "Soundtrack",
                            Slug = "soundtrack"
                        },
                        new
                        {
                            Id = new Guid("120c9c3d-ce2a-4b87-92bf-026971464ac3"),
                            Name = "Other",
                            Slug = "other"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7a8ea12-ae85-461b-bdcb-317e971a6518"),
                            Name = "Lo-Fi",
                            Slug = "lo-fi"
                        },
                        new
                        {
                            Id = new Guid("2304cc02-9d55-49dc-8b97-109a24cff6d2"),
                            Name = "Shoegaze",
                            Slug = "shoegaze"
                        },
                        new
                        {
                            Id = new Guid("73439cec-c616-4b57-bf93-ce6bca127d48"),
                            Name = "Rock",
                            Slug = "rock"
                        },
                        new
                        {
                            Id = new Guid("2d1c3b37-cf4a-4b14-b5cb-68bb4bb73419"),
                            Name = "Pop",
                            Slug = "pop"
                        },
                        new
                        {
                            Id = new Guid("1df62086-0fb8-48d0-bd66-076733f17051"),
                            Name = "Electronic",
                            Slug = "Electronic"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TagTrack", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("TagTracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.ArtistType", "ArtistType")
                        .WithMany("Artists")
                        .HasForeignKey("ArtistTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistType");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistUser", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany("ArtistUsers")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.ReleaseType", "ReleaseType")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseType");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseArtist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TagTrack", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Track", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TrackArtist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.Navigation("ArtistUsers");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistType", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseType", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
