// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musdis.MusicService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicService.Migrations
{
    [DbContext(typeof(MusicServiceDbContext))]
    [Migration("20240504121842_AddCoverUrlToTrackModel")]
    partial class AddCoverUrlToTrackModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ArtistTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72fb8b0e-c5e3-4f13-89ee-2e51fef84a74"),
                            Name = "Band",
                            Slug = "band"
                        },
                        new
                        {
                            Id = new Guid("627789f8-6120-47f2-aaa3-deb85ffb79b3"),
                            Name = "Musician",
                            Slug = "musician"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistUser", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId", "UserId");

                    b.ToTable("ArtistUsers");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReleaseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseArtist", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("ReleaseId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ReleaseArtists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ReleaseTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fdd6237-6f4c-49f8-9c15-09c9fe10e297"),
                            Name = "EP",
                            Slug = "ep"
                        },
                        new
                        {
                            Id = new Guid("c324de6a-2ee4-481c-97fe-ac06e89b3642"),
                            Name = "Album",
                            Slug = "album"
                        },
                        new
                        {
                            Id = new Guid("d18f7426-f75b-4ce6-a25e-27ffa26a18c6"),
                            Name = "Single",
                            Slug = "single"
                        },
                        new
                        {
                            Id = new Guid("648fb1ea-b2f0-441e-8eb6-72e2d2015a79"),
                            Name = "Soundtrack",
                            Slug = "soundtrack"
                        },
                        new
                        {
                            Id = new Guid("ed6f65fd-87b0-4f06-8236-5f42f0e823c0"),
                            Name = "Other",
                            Slug = "other"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("455b9a55-5569-4d8b-8150-ef6fc8cbcb09"),
                            Name = "Lo-Fi",
                            Slug = "lo-fi"
                        },
                        new
                        {
                            Id = new Guid("5124a6d7-80b8-42b8-bba6-daa8642e7b14"),
                            Name = "Shoegaze",
                            Slug = "shoegaze"
                        },
                        new
                        {
                            Id = new Guid("fece3b9e-4b08-4b2d-8111-f86b049d5cfa"),
                            Name = "Rock",
                            Slug = "rock"
                        },
                        new
                        {
                            Id = new Guid("39e89b8b-33a6-4381-9476-7e9c34d7aa94"),
                            Name = "Pop",
                            Slug = "pop"
                        },
                        new
                        {
                            Id = new Guid("07ca573c-8aa7-45ad-a8b3-ceeb12876571"),
                            Name = "Electronic",
                            Slug = "Electronic"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TagTrack", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("TagTracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AudioFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.ArtistType", "ArtistType")
                        .WithMany("Artists")
                        .HasForeignKey("ArtistTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistType");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistUser", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany("ArtistUsers")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.ReleaseType", "ReleaseType")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseType");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseArtist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TagTrack", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Track", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TrackArtist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.Navigation("ArtistUsers");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistType", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseType", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
