// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musdis.MusicService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicService.Migrations
{
    [DbContext(typeof(MusicServiceDbContext))]
    [Migration("20240229085659_AddCreatorIdToTrackAndRelease")]
    partial class AddCreatorIdToTrackAndRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ArtistTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b861f3d7-c02f-4d7b-bfce-4e8a224e5afa"),
                            Name = "Band",
                            Slug = "band"
                        },
                        new
                        {
                            Id = new Guid("9e485c47-461c-4cc0-874a-e9d2d469461e"),
                            Name = "Musician",
                            Slug = "musician"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistUser", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId", "UserId");

                    b.ToTable("ArtistUsers");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReleaseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseArtist", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("ReleaseId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ReleaseArtists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ReleaseTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("163dd204-d500-4769-b352-9cf921c66ff0"),
                            Name = "EP",
                            Slug = "ep"
                        },
                        new
                        {
                            Id = new Guid("e479477a-c26e-49a2-b1a4-f6b82597612f"),
                            Name = "Album",
                            Slug = "album"
                        },
                        new
                        {
                            Id = new Guid("6b8f2f94-1ec3-4d65-84d1-141324014a38"),
                            Name = "Single",
                            Slug = "single"
                        },
                        new
                        {
                            Id = new Guid("13d6da3a-1d10-4543-81b4-239df1a8f310"),
                            Name = "Soundtrack",
                            Slug = "soundtrack"
                        },
                        new
                        {
                            Id = new Guid("f37c03aa-7500-44f3-9c3f-510a63c271ed"),
                            Name = "Other",
                            Slug = "other"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2da9bb5b-1c82-48a8-b0ff-b5a531235c7d"),
                            Name = "Lo-Fi",
                            Slug = "lo-fi"
                        },
                        new
                        {
                            Id = new Guid("c74d5032-e3a9-4309-8cf5-b57e6f255149"),
                            Name = "Shoegaze",
                            Slug = "shoegaze"
                        },
                        new
                        {
                            Id = new Guid("1d85e803-f3d9-4c08-a5b1-fdc6404280a4"),
                            Name = "Rock",
                            Slug = "rock"
                        },
                        new
                        {
                            Id = new Guid("85419c9c-1f96-44ad-a91f-6c1d8f590fc8"),
                            Name = "Pop",
                            Slug = "pop"
                        },
                        new
                        {
                            Id = new Guid("e00ee89e-053e-467d-a6cf-0ebf2df80ff0"),
                            Name = "Electronic",
                            Slug = "Electronic"
                        });
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TagTrack", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("TagTracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.ArtistType", "ArtistType")
                        .WithMany("Artists")
                        .HasForeignKey("ArtistTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistType");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistUser", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany("ArtistUsers")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.ReleaseType", "ReleaseType")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseType");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseArtist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TagTrack", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Track", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.TrackArtist", b =>
                {
                    b.HasOne("Musdis.MusicService.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musdis.MusicService.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Artist", b =>
                {
                    b.Navigation("ArtistUsers");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ArtistType", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.Release", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Musdis.MusicService.Models.ReleaseType", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
